<?php

namespace App\Console\Commands;

use App\Models\RecurringTransaction;
use App\Models\Transaction;
use App\Models\Wallet;
use App\Services\BudgetAlertService;
use App\Services\GoalAutoTopupService;
use Carbon\Carbon;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Log;

class ProcessRecurringTransactions extends Command
{
    protected $signature = 'recurring:process {--dry-run : Show due items without writing transactions}';

    protected $description = 'Process due recurring transactions and materialize them into transactions';

    public function handle(BudgetAlertService $budgetAlertService, GoalAutoTopupService $goalAutoTopupService): int
    {
        $now = now();
        $dryRun = (bool) $this->option('dry-run');
        $processed = 0;
        $failed = 0;

        $dueItems = RecurringTransaction::where('active', true)
            ->where('next_run_at', '<=', $now)
            ->where(function ($q) use ($now) {
                $q->whereNull('end_date')
                    ->orWhere('end_date', '>=', $now->copy()->startOfDay());
            })
            ->orderBy('next_run_at', 'asc')
            ->get();

        foreach ($dueItems as $item) {
            $wallet = Wallet::where('_id', (string) $item->wallet_id)
                ->where('user_id', (string) $item->user_id)
                ->first();

            if (!$wallet) {
                $failed++;
                $this->markFailed($item, 'wallet_missing', 'Wallet linked to recurring transaction not found');
                continue;
            }

            $amount = (float) $item->amount;
            $signed = ((string) $item->type) === 'income' ? $amount : (-1 * $amount);
            $newBalance = (float) $wallet->balance + $signed;

            if ($newBalance < 0) {
                $failed++;
                $item->update([
                    'last_error_code' => 'insufficient_balance',
                    'last_error_message' => 'Insufficient wallet balance for recurring expense',
                    'next_run_at' => $this->calculateNextRun(Carbon::parse($item->next_run_at), (string) $item->frequency, (int) $item->interval),
                ]);

                Log::warning('recurring_insufficient_balance', [
                    'recurring_id' => (string) $item->_id,
                    'wallet_id' => (string) $wallet->_id,
                    'user_id' => (string) $item->user_id,
                    'amount' => $amount,
                    'balance' => (float) $wallet->balance,
                ]);
                continue;
            }

            if (!$dryRun) {
                $transaction = Transaction::create([
                    'user_id' => (string) $item->user_id,
                    'wallet_id' => (string) $item->wallet_id,
                    'type' => (string) $item->type,
                    'source' => $item->source,
                    'category' => $item->category,
                    'total_amount' => $amount,
                    'date' => Carbon::parse($item->next_run_at),
                    'merchant_name' => $item->merchant_name ?: 'Recurring',
                    'notes' => $item->notes ?: 'Generated by recurring schedule',
                    'is_verified' => (bool) $item->is_verified,
                    'tags' => is_array($item->tags ?? null) ? $item->tags : [],
                    'items' => [],
                    'ocr_status' => 'none',
                    'ocr_confidence' => null,
                    'ocr_raw' => null,
                ]);
                $wallet->update(['balance' => $newBalance]);
                if ((string) $item->type === 'expense') {
                    $budgetAlertService->checkAndNotify((string) $item->user_id, (string) $item->category);
                } else {
                    $goalAutoTopupService->applyForIncomeTransaction($transaction);
                }
            }

            $processed++;
            $nextRun = $this->calculateNextRun(
                Carbon::parse($item->next_run_at),
                (string) $item->frequency,
                (int) $item->interval
            );

            $item->update([
                'last_run_at' => $now,
                'next_run_at' => $nextRun,
                'total_runs' => (int) ($item->total_runs ?? 0) + 1,
                'last_error_code' => null,
                'last_error_message' => null,
            ]);

            Log::info('recurring_processed', [
                'recurring_id' => (string) $item->_id,
                'user_id' => (string) $item->user_id,
                'wallet_id' => (string) $item->wallet_id,
                'next_run_at' => $nextRun->toIso8601String(),
                'dry_run' => $dryRun,
            ]);
        }

        $this->info("Recurring processing done: processed={$processed}, failed={$failed}, dry_run=".($dryRun ? 'true' : 'false'));

        return self::SUCCESS;
    }

    private function calculateNextRun(Carbon $current, string $frequency, int $interval): Carbon
    {
        $step = max(1, $interval);

        return match ($frequency) {
            'daily' => $current->copy()->addDays($step),
            'weekly' => $current->copy()->addWeeks($step),
            default => $current->copy()->addMonthsNoOverflow($step),
        };
    }

    private function markFailed(RecurringTransaction $item, string $code, string $message): void
    {
        $item->update([
            'last_error_code' => $code,
            'last_error_message' => $message,
        ]);

        Log::error('recurring_failed', [
            'recurring_id' => (string) $item->_id,
            'user_id' => (string) $item->user_id,
            'error_code' => $code,
            'message' => $message,
        ]);
    }
}
