abstract class RoutePaths {
  static const splash = '/splash';
  static const onboarding = '/onboarding';
  static const login = '/login';
  static const register = '/register';
  static const home = '/home';
  static const analytics = '/analytics';
  static const wallet = '/wallet';
  static const addWallet = '/add-wallet';
  static const manageCategory = '/manage-category';
  static const manageCategoryAlt = '/manage-category-alt';
  static const manageCategoryLegacy = '/manage-category-2';
  static const scan = '/scan';
  static const scanReceipt = '/scan-receipt';
  static const profile = '/profile';
  static const profilePersonalInfo = '/profile/personal-info';
  static const profileNotifications = '/profile/notifications';
  static const profileChangePassword = '/profile/change-password';
  static const profileHelpCenter = '/profile/help-center';
  static const profileAbout = '/profile/about';
  static const profileAiOcrHealth = '/profile/ai-ocr-health';
  static const profileAiFinanceChat = '/profile/ai-finance-chat';
  static const goals = '/goals';
  static const goalsDetail = '/goals/:id';
  static const analyticsFilter = '/analytics/filter';
  static const analyticsExport = '/analytics/export';
  static const recurringTransactions = '/recurring-transactions';

  // ---- Organization accounting ----
  static const orgDashboard = '/org/dashboard';
  static const orgBalanceSheet = '/org/balance-sheet';
  static const orgActivities = '/org/activities';
  static const orgTrialBalance = '/org/trial-balance';
  static const orgJournal = '/org/journal';
  static const orgJournalNew = '/org/journal/new';
  static const orgLedger = '/org/ledger';
  static const orgAccounts = '/org/accounts';
  static const orgFixedAssets = '/org/fixed-assets';
  static const orgReceivablesPayables = '/org/receivables-payables';
  static const orgRestrictedFunds = '/org/restricted-funds';
  static const orgImport = '/org/import';
  static const orgAiChat = '/org/ai-chat';
  static const orgScan = '/org/scan-struk';
  static const orgRecurring = '/org/recurring';
  static const orgBudget = '/org/budget';
  static const orgMembers = '/org/members';
  static const orgInviteAccept = '/org-invite/:token';
}
